kind = "web"
previewPath = "/"
title = "Rafael Tavares Corretor"
version = "1.0.0"

[[services]]
localPort = 3001
name = "web"
paths = ["/"]

[services.development]
run = "node serve.js"

[services.development.env]
PORT = "3001"
